# GitHub Dependabot configuration
# Keeps dependencies up to date automatically

version: 2
updates:
  # Maven dependencies
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 5
    reviewers:
      - "@me"
    assignees:
      - "@me"
    commit-message:
      prefix: "deps"
      include: "scope"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly" 
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 3
    reviewers:
      - "@me"
    assignees:  
      - "@me"
    commit-message:
      prefix: "ci"
      include: "scope"